# Harbor - Sleep mechanics enhancement plugin
# An open-source project by TechToolbox (@nkomarn)
# https://github.com/nkomarn/Harbor

night-speed:
  enabled: true # Whether to increase night speed dynamically based on number of players sleeping
  min-speed-multiplier: 2 # The minimum night speed when at least one player is sleeping
  max-speed-multiplier: 10 # The maximum night speed when all players are sleeping, unless settings below are configured

night-skip:
  enabled: true # Whether to skip the night at a fixed or instant speed once the given threshold of sleeping players has been hit
  skip-percentage: 50 # Percentage of players required to be sleeping to skip the night (0 - 100)
  instant-skip: true # Whether to skip night instantly when the threshold is hit
  skip-speed-multiplier: 30 # Speed multiplier to use if the instant skipping is disabled

morning:
  clear-rain: true # Clear rain (if it's raining) when the night is skipped
  clear-thunder: true # Clear thunder (if it's thundering) when the night is skipped
  play-sound: 'minecraft:entity.player.levelup'

exclusions:
  ignored-permission: true # Exclude players with the permission "harbor.ignored" from the sleeping count
  exclude-survival: false # Exclude players in survival mode from the sleeping count
  exclude-adventure: false # Exclude players in adventure mode from the sleeping count
  exclude-creative: false # Exclude players in creative mode from the sleeping count
  exclude-spectator: true # Exclude players in spectator mode from the sleeping count
  exclude-vanished: true # Exclude vanished players from the sleeping count

# Blacklist
# If paper's time.affects-all-worlds setting is enabled, Harbor will treat this list as a list of world clocks to ignore
# Otherwise, Harbor will treat this list as a list of worlds to ignore
blacklist:
  - "minecraft:the_end"
whitelist-mode: false # Will treat the above list as a whitelist instead of a blacklist

messages:
  title:
    enabled: true
    sleep-title: '<aqua><12h>:<min> <mer_upper>'
    sleep-subtitle: '<green><sleeping>/<players> Sleeping <dark_aqua>(<timescale>x speed)'
    morning-title: '<yellow><12h>:<min> <mer_upper>'
    morning-subtitle: '<green>Rise and shine, <displayname>!'
    stay-ticks: 20
    fade-ticks: 40
  bossbar:
    enabled: true
    message: "<green><sleeping>/<players> Sleeping <dark_aqua>- <aqua><12h>:<min> <mer_upper> (<timescale>x speed)"
    color: GREEN
  miscellaneous:
    chat-prefix: "<dark_gray><bold>(<gold><bold>Harbor<dark_gray><bold>)<reset> "

# Spooky internal controls
version: 1.6.4
interval: 10
debug: false
