# Harbor - Sleep mechanics enhancement plugin
# An open-source project by TechToolbox (@nkomarn)
# https://github.com/nkomarn/Harbor

# Important note regarding Essentials:
# Please make sure you negate the permission "essentials.sleepingignored" to
# prevent issues with Harbor and server operators when running Essentials.

night-speed:
  enabled: true # Whether to increase night speed dynamically based on number of players sleeping
  min-speed-multiplier: 2 # The minimum night speed when at least one player is sleeping
  max-speed-multiplier: 10 # The maximum night speed when all players are sleeping, unless settings below are configured

night-skip:
  enabled: true # Whether to skip the night at a fixed or instant speed once the given threshold of sleeping players has been hit
  skip-percentage: 50 # Percentage of players required to be sleeping to skip the night (0 - 100)
  instant-skip: true # Whether to skip night instantly when the threshold is hit
  skip-speed-multiplier: 30 # Speed multiplier to use if the instant skipping is disabled

morning:
  clear-rain: true # Clear rain (if it's raining) when the night is skipped
  clear-thunder: true # Clear thunder (if it's thundering) when the night is skipped
  reset-phantom-statistic: true # Treats everyone online as if they have slept in the last 3 days after the night is skipped (check out /gamerule doInsomnia on 1.15+)

exclusions:
  ignored-permission: true # Exclude players with the permission "harbor.ignored" from the sleeping count
  exclude-survival: false # Exclude players in survival mode from the sleeping count
  exclude-adventure: false # Exclude players in adventure mode from the sleeping count
  exclude-creative: false # Exclude players in creative mode from the sleeping count
  exclude-spectator: true # Exclude players in spectator mode from the sleeping count
  exclude-vanished: true # Exclude vanished players from the sleeping count
  exclude-afk: true # Exclude players who are considered afk from the sleeping count

# Detect AFK players and automatically remove them from the required sleeping count
# Essentials API is used for AFK detection when available- otherwise a fallback system is used
afk-detection:
  fallback-enabled: true
  essentials-enabled: true
  essentials-detection-mode: and # Plugins providing an AFK status, such as Essentials, can either have that AFK check ANDed or ORed with other plugin's checks. By default, we use ANDed detection (Essentials AND any other plugins must report the player as AFK)
  fallback-timeout: 15 # Time in minutes until a player is considered AFK

# Blacklist for worlds- Harbor will ignore these worlds
blacklisted-worlds:
  - "world_nether"
  - "world_the_end"
whitelist-mode: false # Will treat the above list as a whitelist instead of a blacklist

messages:
  bossbar:
    enabled: true
    message: "&a[sleeping]/[players] Sleeping &3- &b[12h]:[min] [mer_upper] ([timescale]x speed)"
    color: GREEN
  miscellaneous:
    chat-prefix: "&8&l(&6&lHarbor&8&l)&f "
    unrecognized-command: "Unrecognized command."

# Spooky internal controls
version: 1.6.4
interval: 10
debug: false
