[versions]
pluginYmlPaper = "0.9.0"
paper = "26.2.build.+"
placeholderApi = "2.12.3"
paperweightUserdev = "2.0.0-beta.21"

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
paperweightBundle = { group = "io.papermc.paper", name = "dev-bundle", version.ref = "paper" }
placeholderApi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderApi" }

[plugins]
pluginYmlPaper = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYmlPaper" }
paperweightUserdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweightUserdev" }
